import os
import sys

# Add current directory to path for imports
sys.path.insert(0, os.path.abspath("."))

from src.state import Player, WorldState
from src.schemas import CharacterProfile
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

from src.llm_client import LLMClient
from src.lore_validator import LoreParser, LoreValidator, create_validator

console = Console()

def initialize_game(llm: LLMClient) -> Player:
    console.print("[blue]Welcome to the Story Engine PoC[/blue]")
    console.print("[blue]Who are you, and what do you seek?[/blue]\n")

    backstory = console.input("[blue]>[/blue] Enter your backstory: ")

    system_prompt = llm._load_system_prompt()

    console.print("\n[yellow]=== System Prompt Preview ===[/yellow]")
    console.print(system_prompt[:500] + "[\n\n", markup=False)

    try:
        with console.status("[yellow]Parsing background with local LLM...[/yellow]"):
            profile = llm.generate_structured(system_prompt, backstory, CharacterProfile)
    except Exception as e:
        console.print(f"\n[red]Error parsing your backstory: {e}[/red]")
        console.print("[yellow]Please try with a clearer backstory or check your network.[/yellow]")
        return None

    # === Lore Validation ===
    console.print("\n[yellow]=== Validating against lore database ===[/yellow]")

    # Initialize lore validator
    parser = LoreParser(console)
    parser.parse_markdown("data/lore_summary.md")
    validator = LoreValidator(parser, console=console)

    result = validator.validate_input(backstory)
    is_valid = result.is_valid
    conflicts = result.conflicts
    suggestions = result.suggestions
    # Track the currently-used profile (starts as what was parsed from user's input)
    current_profile = profile
    current_backstory = backstory

    if not is_valid:
        console.print(Panel(
            "[red]The extracted character profile conflicts with established lore.[/red]\n"
            f"[yellow]Conflicts found: {len(conflicts)}[/yellow]",
            title="Lore Conflict Detected",
            border_style="red",
            box=box.DOUBLE
        ))

        # Negotiation loop
        max_attempts = 5
        attempts = 0

        while conflicts and attempts < max_attempts:
            attempts += 1
            console.print(f"\n[gray]Attempt {attempts}/{max_attempts}[/gray]")

            # Show conflict details
            for i, conflict in enumerate(conflicts, 1):
                severity_marker = {
                    "error": "[red][!]",
                    "warning": "[yellow][!]",
                    "info": "[cyan][i]"
                }.get(conflict.severity, "[?]")
                console.print(f"{severity_marker} {conflict.fact.fact}")

            # Build revision options (concrete backstories generated by validator's LLM)
            revision_options = None
            if suggestions:
                table = Table(
                    title="Suggested Revisions",
                    box=box.SIMPLE,
                    show_header=True,
                    header_style="bold cyan"
                )
                table.add_column("Option", style="cyan")
                for i, suggestion in enumerate(suggestions, 1):
                    # Truncate long suggestions for display
                    display = suggestion[:200] + "..." if len(suggestion) > 200 else suggestion
                    table.add_row(f"[i]Option {i}:[/i] {display}")

                console.print(table)
                revision_options = suggestions

            # Ask user how to proceed
            response = console.input(
                "\n[bold yellow]How would you like to proceed?[/bold yellow]\n"
                "[yellow] (a) Accept suggested revision option below[/yellow]\n"
                "[yellow] (r) Revise the input yourself[/yellow]\n"
                "[yellow] (s) Skip this validation[/yellow]\n"
                "> "
            )

            if "a" in response.lower():
                if not revision_options:
                    console.print("\n[yellow]No suggestions available. Please revise manually.[/yellow]")
                    continue

                # Show concrete revision options for the user to pick from
                console.print("\n[bold]Choose a revision option (1, 2, or 3):[/bold]")
                for i, opt in enumerate(revision_options[:3], 1):
                    safe_opt = opt if not opt.startswith("Revised:") else opt[len("Revised:"):].strip()
                    console.print(f"  [cyan]{i}.[/cyan] {safe_opt}")

                choice = console.input("> ").strip()
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(revision_options):
                        revised_backstory = revision_options[idx]
                        console.print(f"\n[yellow]You selected option {idx+1}. Parsing...[/yellow]")

                        # Parse the selected revision through the LLM to get a new profile
                        rev_system_prompt = llm._load_system_prompt()
                        revised_profile = llm.generate_structured(rev_system_prompt, revised_backstory, CharacterProfile)

                        # Re-validate
                        result = validator.validate_input(revised_backstory)
                        is_valid = result.is_valid
                        conflicts = result.conflicts
                        suggestions = result.suggestions

                        if is_valid:
                            current_profile = revised_profile
                            current_backstory = revised_backstory
                    else:
                        console.print("[yellow]Invalid option. Please try again.[/yellow]")
                except ValueError:
                    console.print("[yellow]Invalid input. Expected a number (1, 2, or 3).[/yellow]")
            elif "r" in response.lower():
                # User wants to revise
                console.print("\n[blue]=== Please revise your backstory ===[/blue]")
                console.print("[yellow]Make it consistent with the lore:[/yellow]")
                console.print("[dim](e.g., choose an existing faction, adjust magic usage, etc.)[/dim]\n>")
                revised_backstory = console.input("> ")

                # Re-parse the revised backstory through the LLM to get a new profile
                system_prompt = llm._load_system_prompt()
                try:
                    revised_profile = llm.generate_structured(system_prompt, revised_backstory, CharacterProfile)
                except Exception as e:
                    console.print(f"\n[red]Error parsing your revised backstory: {e}[/red]")
                    console.print("[yellow]Please try again or use a different revision.[/yellow]")
                    continue

                # Re-validate the revised input
                result = validator.validate_input(revised_backstory)
                is_valid = result.is_valid
                conflicts = result.conflicts
                suggestions = result.suggestions

                # Use the newly parsed profile if validation passed
                if is_valid:
                    current_profile = revised_profile
                    current_backstory = revised_backstory
            else:
                # Skip validation - warn but continue
                console.print("\n[yellow]Skipping validation. Using extracted profile as-is.[/yellow]")
                conflicts = []
                suggestions = []

        if conflicts and attempts >= max_attempts:
            console.print("\n[red]Could not resolve lore conflicts after multiple attempts.[/red]")
            console.print("[yellow]Character creation failed. Exiting...[/yellow]")
            return None

    # === Create Player Object (use revised profile if available) ===
    player = Player(
        name="Protagonist",
        faction=current_profile.origin_faction,
        motivation=current_profile.motivation,
        goal=current_profile.goal
    )

    # === Display Format 1: Structured Block ===
    console.print("\n[green]=== Character Established ===[/green]")
    console.print(f"[italic]Faction:[/italic] [bold white]{player.faction}[/bold white]")
    console.print(f"[italic]Motivation:[/italic] [bold red]{player.motivation}[/bold red]")
    console.print(f"[italic]Goal:[/italic] [bold cyan]{player.goal}[/bold cyan]")

    # === Display Format 2: Narrative Paragraph ===
    console.print("\n[green]=== Character Profile ===[/green]")
    console.print(Panel(
        f"[bold]{player.name}[/bold]\n"
        f"A [bold]{player.faction}[/bold] driven by [bold]{player.motivation}[/bold],\n"
        f"seeking to [bold]{player.goal}[/bold].",
        title="Character Profile",
        border_style="blue"
    ))

    return player

def main():
    llm = LLMClient()
    world = WorldState(current_location="Starting Village")

    player = initialize_game(llm)

    if player:
        console.print("\n[blue]--- Engine Initialized. Ready for Game Loop. ---[/blue]")
    else:
        console.print("\n[red]Failed to initialize character. Exiting...[/red]")
        sys.exit(1)


if __name__ == "__main__":
    main()
